# Generated by Django 5.0.7 on 2024-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PNR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pnr_number", models.CharField(max_length=10, unique=True)),
                ("is_valid", models.BooleanField(default=False)),
            ],
        ),
    ]
