# Generated by Django 5.0.7 on 2024-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pnr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="reviews",
        ),
        migrations.AddField(
            model_name="parcel",
            name="origin",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
